site_name: Archery
theme: material
pages:
- 'Overview': 'index.md'
- 'Getting started': 'install.md'
- 'Setting up the Environment': 'setupGuide.md'
- 'Install in Kali': 'kaliGuide.md'
- 'Developers': 'developers.md'
- Contributors: 'contributors.md'
- Roadmap: 'roadmap.md'

# Options
extra:
  feature:
    tabs: true
  palette:
    primary: deep purple
    accent: indigo
  social:
    - type: github-alt
      link: https://github.com/archerysec/archerysec
    - type: twitter
      link: https://twitter.com/archerysec
    - type: facebook
      link: https://www.facebook.com/ArcherySec/

# Project information
site_description: All about ArcherySec.
site_author: Anand Tiwari
site_url: https://github.com/archerysec/archerysec

# Repository
repo_name: archerysec/archerysec
repo_url: https://github.com/archerysec/archerysec
